theme: jekyll-theme-minimal
title: Yeti-Dancing-On-Checkered-Board
description: Experiment with BabylonJS and Deployment on GitHub Pages. Actual Project of Rendering 3D Models of Human Anatomy will not be Shown in Public Repo.
